/// DevAudit
///
/// Copyright (c) Pharos Labs.
/// Licensed under the Apache License, Version 2.0.
library;

import 'dart:io';

import '../../core/model/audit_context.dart';
import '../../core/model/audit_issue.dart';
import '../../core/plugin/audit_plugin.dart';
import '../../core/rule/audit_rule_metadata.dart';
import '../../shared/path_normalizer.dart';
import 'analyzer/dart_file_analyzer.dart';
import 'flutter_file_discovery.dart';
import 'rules/hardcoded_ui_string_rule.dart';

/// The built-in plugin that audits Flutter/Dart projects.
///
/// This is the first concrete [AuditPlugin] implementation. It discovers
/// Dart source files under the target project, parses each with
/// `package:analyzer`, and runs the rules it owns against the resulting
/// AST. All Flutter- and Dart-specific knowledge lives here and in the
/// files this plugin owns; the core engine and CLI never reference either.
///
/// Since: 0.1.0-dev.1
class FlutterAuditPlugin extends AuditPlugin {
  /// Creates the Flutter audit plugin.
  const FlutterAuditPlugin({
    this.fileDiscovery = const FlutterFileDiscovery(),
    this.analyzer = const DartFileAnalyzer(),
    this.rule = const HardcodedUiStringRule(),
  });

  /// Discovers which Dart files to analyze.
  final FlutterFileDiscovery fileDiscovery;

  /// Parses Dart source into an AST.
  final DartFileAnalyzer analyzer;

  /// The localization rule this plugin currently implements.
  final HardcodedUiStringRule rule;

  @override
  String get id => 'flutter';

  @override
  String get displayName => 'Flutter';

  @override
  List<AuditRuleMetadata> get rules => [rule.metadata];

  @override
  bool supports(String filePath) => filePath.endsWith('.dart');

  /// Analyzes [context] and returns the issues found.
  ///
  /// `filesScanned` on the returned [PluginAnalysisResult] counts only
  /// files a parse was actually attempted on: a file skipped before
  /// parsing (unreadable, or recognized as generated by its content
  /// header) is not counted, while a file that parsed with syntax errors
  /// *is* counted, since a parse attempt genuinely happened before that
  /// file was skipped.
  @override
  Future<PluginAnalysisResult> analyze(AuditContext context) async {
    final files = fileDiscovery.discover(
      context.projectRoot,
      include: context.include,
      exclude: context.exclude,
    );

    final issues = <AuditIssue>[];
    var filesScanned = 0;

    for (final file in files) {
      final String content;
      try {
        content = file.readAsStringSync();
      } on FileSystemException {
        // Unreadable file (permissions, broken symlink target, etc.): skip
        // it and keep auditing the rest of the project.
        continue;
      }

      if (content.contains(generatedFileHeaderMarker)) continue;

      final relativePath = normalizeRelativePath(
        context.projectRoot,
        file.path,
      );
      final parseResult = analyzer.parse(path: file.path, content: content);
      filesScanned++;

      if (analyzer.hasSyntaxErrors(parseResult)) {
        // Syntactically invalid file: skip it rather than crashing the scan.
        continue;
      }

      issues.addAll(
        rule.evaluate(
          relativePath: relativePath,
          source: content,
          unit: parseResult.unit,
          lineInfo: parseResult.lineInfo,
        ),
      );
    }

    return PluginAnalysisResult(issues: issues, filesScanned: filesScanned);
  }
}
