/// DevAudit
///
/// Copyright (c) Pharos Labs.
/// Licensed under the Apache License, Version 2.0.
library;

import 'dart:io';

import 'package:path/path.dart' as p;

import '../../core/model/audit_context.dart';
import '../../core/model/audit_issue.dart';
import '../../core/plugin/audit_plugin.dart';
import '../../core/rule/audit_rule_metadata.dart';
import '../../shared/path_normalizer.dart';
import 'analyzer/dart_file_analyzer.dart';
import 'arb/arb_document.dart';
import 'arb/arb_file_discovery.dart';
import 'arb/arb_file_parser.dart';
import 'flutter_file_discovery.dart';
import 'rules/hardcoded_ui_string_rule.dart';
import 'rules/missing_locale_key_rule.dart';

/// The built-in plugin that audits Flutter/Dart projects.
///
/// This is the first concrete [AuditPlugin] implementation. It discovers
/// Dart source files under the target project, parses each with
/// `package:analyzer`, and runs the rules it owns against the resulting
/// AST. All Flutter- and Dart-specific knowledge lives here and in the
/// files this plugin owns; the core engine and CLI never reference either.
///
/// Since: 0.1.0-dev.1
class FlutterAuditPlugin extends AuditPlugin {
  /// Creates the Flutter audit plugin.
  const FlutterAuditPlugin({
    this.fileDiscovery = const FlutterFileDiscovery(),
    this.analyzer = const DartFileAnalyzer(),
    this.rule = const HardcodedUiStringRule(),
    this.arbFileDiscovery = const ArbFileDiscovery(),
    this.arbFileParser = const ArbFileParser(),
    this.missingLocaleKeyRule = const MissingLocaleKeyRule(),
  });

  /// Discovers which Dart files to analyze.
  final FlutterFileDiscovery fileDiscovery;

  /// Parses Dart source into an AST.
  final DartFileAnalyzer analyzer;

  /// The Dart AST-based localization rule this plugin runs.
  final HardcodedUiStringRule rule;

  /// Discovers which ARB files to analyze.
  final ArbFileDiscovery arbFileDiscovery;

  /// Parses ARB source into an [ArbDocument].
  final ArbFileParser arbFileParser;

  /// The ARB-based localization rule this plugin runs.
  final MissingLocaleKeyRule missingLocaleKeyRule;

  @override
  String get id => 'flutter';

  @override
  String get displayName => 'Flutter';

  @override
  List<AuditRuleMetadata> get rules => [
    rule.metadata,
    missingLocaleKeyRule.metadata,
  ];

  @override
  bool supports(String filePath) =>
      filePath.endsWith('.dart') || filePath.endsWith('.arb');

  /// Analyzes [context] and returns the issues found.
  ///
  /// `filesScanned` on the returned [PluginAnalysisResult] counts only
  /// files a parse was actually attempted on: a file skipped before
  /// parsing (unreadable, or recognized as generated by its content
  /// header) is not counted, while a file that parsed with syntax errors
  /// *is* counted, since a parse attempt genuinely happened before that
  /// file was skipped. This applies uniformly to both the Dart files [rule]
  /// analyzes and the ARB files [missingLocaleKeyRule] analyzes.
  @override
  Future<PluginAnalysisResult> analyze(AuditContext context) async {
    final dartResult = _analyzeDartFiles(context);
    final arbResult = _analyzeArbFiles(context);

    return PluginAnalysisResult(
      issues: [...dartResult.issues, ...arbResult.issues],
      filesScanned: dartResult.filesScanned + arbResult.filesScanned,
    );
  }

  PluginAnalysisResult _analyzeDartFiles(AuditContext context) {
    final files = fileDiscovery.discover(
      context.projectRoot,
      include: context.include,
      exclude: context.exclude,
    );

    final issues = <AuditIssue>[];
    var filesScanned = 0;

    for (final file in files) {
      final String content;
      try {
        content = file.readAsStringSync();
      } on FileSystemException {
        // Unreadable file (permissions, broken symlink target, etc.): skip
        // it and keep auditing the rest of the project.
        continue;
      }

      if (content.contains(generatedFileHeaderMarker)) continue;

      final relativePath = normalizeRelativePath(
        context.projectRoot,
        file.path,
      );
      final parseResult = analyzer.parse(path: file.path, content: content);
      filesScanned++;

      if (analyzer.hasSyntaxErrors(parseResult)) {
        // Syntactically invalid file: skip it rather than crashing the scan.
        continue;
      }

      issues.addAll(
        rule.evaluate(
          relativePath: relativePath,
          source: content,
          unit: parseResult.unit,
          lineInfo: parseResult.lineInfo,
        ),
      );
    }

    return PluginAnalysisResult(issues: issues, filesScanned: filesScanned);
  }

  /// Runs [missingLocaleKeyRule] against every ARB file discovered under
  /// [context].
  ///
  /// At least a reference and one other locale document are required for a
  /// comparison to be meaningful; with fewer than two successfully parsed
  /// ARB documents, this reports zero issues rather than guessing.
  PluginAnalysisResult _analyzeArbFiles(AuditContext context) {
    final files = arbFileDiscovery.discover(context.projectRoot);

    final documents = <ArbDocument>[];
    var filesScanned = 0;

    for (final file in files) {
      final String content;
      try {
        content = file.readAsStringSync();
      } on FileSystemException {
        // Unreadable file: skip it and keep auditing the rest of the
        // project.
        continue;
      }

      filesScanned++;

      final relativePath = normalizeRelativePath(
        context.projectRoot,
        file.path,
      );
      final document = arbFileParser.parse(
        path: relativePath,
        content: content,
      );
      // A malformed (non-JSON, or non-object) ARB file is skipped rather
      // than crashing the scan; a parse attempt genuinely happened, so it
      // is still counted above.
      if (document != null) documents.add(document);
    }

    if (documents.length < 2) {
      return PluginAnalysisResult(issues: const [], filesScanned: filesScanned);
    }

    final reference = documents.firstWhere(
      (document) => p.basename(document.path) == 'app_en.arb',
      orElse: () => documents.first,
    );
    final locales = documents
        .where((document) => document.path != reference.path)
        .toList();

    final issues = missingLocaleKeyRule.evaluate(
      reference: reference,
      locales: locales,
    );
    return PluginAnalysisResult(issues: issues, filesScanned: filesScanned);
  }
}
